---
- name: Setup Dev Environment
  hosts: localhost
  connection: local
  gather_facts: yes
#  become: yes
#  become_user: root
  roles:
      # TODO make this optional
#    - update_packages
    - git
    - bash_profile
    - tmux
    - vim