---
- name: Update Packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    cache_valid_time: 3600

- name: Install desired packages
  ansible.builtin.apt:
    pkg: "{{ packages }}"
    state: present
