---
- git_config:
    name: core.editor
    scope: global
    value: vim

- git_config:
      name: user.name
      scope: global
      value: chatton

- git_config:
      name: user.email
      scope: global
      value: github.qpeyb@simplelogin.fr