---
- name: setup git name
  git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"
- name: setup git user email
  git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"
